# -- 主菜单（页面顶部导航）--
[[main]]
  name = "博客"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "知识库"
  pageRef = "learning"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 40

# -- 页脚菜单 --
[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "分类"
  pageRef = "categories"
  weight = 20
